### ISSUE TITLE
Recumbobulating a map-condom soft-locks the player.

### ISSUE THREAD

**Issue by naelstrof** [Archival1/CV-BugReporting#10]
**Describe the bug**
Recumbobulating a map-condom soft-locks the player.

**To Reproduce**
1. Load level Station
2. Grab condom in priest room.
3. Attempt to recumbobulate it at a machine.

**Comment by without-ordinary** [comment]
Related: The 2 of the condoms under the shelf in front of the door are trapped.

When I tried to repo, the player repeats the use animation but this can be canceled. There is an opportunity for an easter egg with these or something.

**Comment by naelstrof** [comment]
Fixed as of 5380ef79. Condoms simply get destroyed rather than trying to enable a non-existent npc. We didn't do an easter egg, this might change later.
