### ISSUE TITLE
NPC's can clip through and see through lockers

### ISSUE THREAD

**Issue by Blueblaze95** [Archival1/CV-BugReporting#11]
**Describe the bug**
NPC can walk through the lockers and see the player through the locker. Players cannot interact with NPC while they are clipped in a locker.

**To Reproduce**
1. Load level 'City'
2. Go to the kitchen
3. Lockers in the kitchen by the corridor
4. Have an NPC on the other side of the locker and do not crouch.

**Expected behavior**
The NPC will run through the locker and stand there. Unable to be interacted with until they become panicked and run away.

**Desktop (please complete the following information):**
 - OS: Windows
 - Graphics Card: Nvidia
 - Version: cef91e5c

**Comment by Blueblaze95** [comment]
Just something else I noticed about them, it looks like the collision is disabled for those lockers. You can walk right through them and can't interact with them.

**Comment by Archival1** [comment]
Tested and reproduced

**Comment by Archival1** [comment]
Fix for this will be included in the next update, thanks for the report!
