### ISSUE TITLE
Pressing second floor warehouse button twice leads to softlock

### ISSUE THREAD

**Issue by itsbirdseed** [Archival1/CV-BugReporting#12]
**Describe the bug**
After pressing the button on the second floor of the warehouse that opens the door below, pressing again will zoom the camera in on the door and lock the player in the cutscene, requiring a level restart to escape.

**To Reproduce**
1. Load warehouse
2. Go to the second floor room with the button
3. Interact with the button
4. Interact with the button again

**Expected behavior**
The door closes and the cutscene ends.

**Screenshots**
![hhh](https://github.com/Archival1/CV-BugReporting/assets/45325998/756cc1cd-b509-4f5c-8fb2-6aa4280202cb)

**Desktop:**
 - OS: Windows 10
 - Graphics Card: Nvidia RTX 2070 Super
 - Version: cef91e5c

**Comment by Archival1** [comment]
Tested and reproduced

**Comment by Archival1** [comment]
Action by @naelstrof - fixed in the next release
