### ISSUE TITLE
Tail of Priest Rat

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#14]
**Describe the bug**
Her tail just disappears when she becomes naked. Also, her tail not visible at scan mode.

**To Reproduce**
1. Load level 'Station'
2. Grab target Priest Rat and wait when her clothes become removed
3. See error

**Expected behavior**
Looks like a bug, she have tail when wearing clothes. It is inflatable tail?

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics Card AMD 6600XT
 - Version cef91e5c

**Additional context**
Even if that is a bug - it sounds really fun secret detail if some characters will have "artificial" detail that disappear after CV and respawn.

**Comment by Archival1** [comment]
Tested and reproduced - yes its a bug

**Comment by Archival1** [comment]
Will be fixed in the next update
