### ISSUE TITLE
3 Guards get stuck in 4 table room near captain on Station

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#16]
**Describe the bug**
3 guards apparently start in this room and are stuck in the chairs/floor. I suspect they are intended to start seated.

**To Reproduce**
1. Load Station
2. Navigate around level to captain's area. The route CCW around the level through the vent to the locker room with the guard GH works.

**Expected behavior**
The 3 guards not to be stuck. (Does make the level easier though. lol)

**Screenshots**
![20240122003034_1](https://github.com/Archival1/CV-BugReporting/assets/20104884/ad266f94-3c99-43a5-8b28-acc7d1812162)

**Desktop (please complete the following information):**
- OS: Linux
- Graphics Card: NVIDIA 3090
- Version: 1/19/2024_cef91e5c

**Additional context**
They are unable to move even when alerted but can attack.

**Comment by Archival1** [comment]
Reproduced, i'll get on this one soon.

**Comment by Archival1** [comment]
Seats now handle character IK's better and as a result this bug will be fixed in the next update
