### ISSUE TITLE
Dialogue sticks when cancelling NPC interaction

### ISSUE THREAD

**Issue by Archival1** [Archival1/CV-BugReporting#2]
**Describe the bug**
If an NPC is 'speaking' via the dialogue popups during the use of any breeding station, the dialogue will remain forever if the player cancels the use before the dialogue vanishes.

**To Reproduce**
1. Load Office
2. Interact with the glory hole kangaroo in the closest bathroom to spawn
3. Cancel the interaction while the NPC is 'speaking'

**Expected behavior**
Dialogue should continue as normal and then vanish (or simply vanish immediately)

**Desktop (please complete the following information):**
 - OS: Windows
 - Graphics Card: RTX 3070
 - Version: 1/11/1024_cfdce05f

**Additional context**
This issue was initially raised by a user via the KK discord and was able to reliably reproduce it with the Girrafe bathroom stations

**Comment by naelstrof** [comment]
Fixed in e2448e2048fce0918e66ce40dd22b1ac5696cf12
