### ISSUE TITLE
Lost character control

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#20]
**Describe the bug**
If someone using recumbobulator while player holding condom near it - player losing control, soft lock state

**To Reproduce**
1. Work for any level
2. Transform two characters into condom state
3. Leave one near any npc, grab another and wait near recumbobulator until the npc start to use it

**Expected behavior**
It should just disappear from hands.

**Screenshots**
Bug's effect not visible on screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics Card AMD 6600XT
 - Version cef91e5c

**Additional context**
Also, same effect works for npc that holding one of condoms - that but completely break npc ability to move and react.
Upd. Their physics become a physics of condom. If put some character at that state - it is possible to play bowling using them.

**Comment by naelstrof** [comment]
Nice find, should be fixed next patch.
