### ISSUE TITLE
Security Personell getting stuck on seats

### ISSUE THREAD

**Issue by MeepusMeepus** [Archival1/CV-BugReporting#22]
**Describe the bug**
On level 'Station', after the latest update, security NPC's are getting stuck after having sat around the 'break table' in the small room close to where the the captain is. This is the room connected to the useable security NPC where you can offload a victim. 

I can only assume that the latest pass over to improve sitting animations means they now go through the floor when they stand up, and get stuck there.

**To Reproduce**
1. Load level 'Station'
2. Hang around near security break room, close to captain and wait for of the security NPCs to have a seat
3. Wait untill they try to get up, or disturb them so they get up prematurely

**Expected behavior**
That the NPCs can walk around after taking a small break, not sentenced to purgatory for daring to sit down on company time :)

**Screenshots**

https://github.com/Archival1/CV-BugReporting/assets/157548449/a82f037c-9935-4f5d-a2a3-d3fe9471fd9c
https://github.com/Archival1/CV-BugReporting/assets/157548449/4c373da0-27a1-42e5-92d9-ad91bec54305

**Desktop (please complete the following information):**
 - OS: Windows
 - Graphics Card : Nvidia 1080Ti
 - Version: cef91e5c

**Additional context**
While the behaviour is random, and thus it takes a random amount of time for the issue to happen, I've seen up to 3 stuck at the same time, and it may be possible for every seat to trap at least 1 NPC, though I don't know if they can all be used.

**Comment by without-ordinary** [comment]
Duplicate of https://github.com/Archival1/CV-BugReporting/issues/16

**Comment by Archival1** [comment]
Closing this as a duplicate, please check the linked ticket for progress and any feedback you want to leave
