### ISSUE TITLE
NPCs unable to use lower elevator in City

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#25]
**Describe the bug**
NPCs get stuck trying to use this elevator from the lower floor. I have not yet been able to observe the upper station to see if it has similar issue (could really use some debug options or cheats, lol).

**To Reproduce**
1. Load level City
2. Got to elevator right of cafeteria
3. Wait for NPC to use call button
4. Observe NPC stuck trying to nav on to elevator platform

**Expected behavior**
NPCs able to use elevator

**Screenshots**
![image](https://github.com/Archival1/CV-BugReporting/assets/20104884/49e7adb3-fc51-4de5-a47d-c94c269bc21c)

**Desktop (please complete the following information):**
 - OS: Linux
 - Graphics Card: Nvidia 3090
 - Version: 1f2310b8

**Additional context**
This leads to something similar to #7 if another NPC tries to use the upper station, neither end up able to move to the other floor as the elevator is just cycled up and down endlessly until one of the NPCs is interrupted.

**Comment by Archival1** [comment]
I've not been able to reproduce this one, possibly a bug with the navmesh in last weeks patch, if this keeps happening after the next one let me know

**Comment by without-ordinary** [comment]
I tested this some more times and it doesn't always happen. Was seeing it somewhat regularly with many other lifts if observed long enough. The dragon especially had a hard time with the center control room lift after eating, but their balls are a big factor to their anti-mobility in general.

**Comment by BlackLordRoo** [comment]
That is a common bug when two npc start "tug of war" with doors or elevators, trying to use it at the same time. Especially often I have seen it at City map. I think there just need incremental cooldown for npc itself when they stuck in loop of repeating actions.

**Comment by naelstrof** [comment]
There was a slightly suspicious navmesh link that was placed very closely to another, might've been a floating point rounding error for the navmesh link detector. I doubt that was the problem though, there must be something more troublesome at play. Those elevators are awfully complex haha.

**Comment by Archival1** [comment]
Gave the elevators a once over and they seem to be working fine, unless other people start running into this soon i'll mark this one as done

**Comment by Archival1** [comment]
Closing this as I haven't heard anything about this since the change
