### ISSUE TITLE
Opossum chief/cook hat obscures alert indicator

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#26]
**Describe the bug**
The opossum chief/cook hat completely blocks the alert indicator. Its only visible if they are doing an animation that moves their head away from their center.

**To Reproduce**
1. Load level any level with an opossum chief or cook, I was using City
2. Let them see you
3. Observe that the alert indicator is completely obscured by hat

**Expected behavior**
Being able to tell if the a hat wearing opossum is sus to player.

**Screenshots**
NPC in animation which allows the indicator to become visible for a moment. In idle, walking, or other some other animations, the indicator is not visible.
![image](https://github.com/Archival1/CV-BugReporting/assets/20104884/aa8b32d3-13e7-40cd-97b9-3127b0f04229)

**Desktop (please complete the following information):**
 - OS: Linux
 - Graphics Card: Nvidia 3090
 - Version: 1f2310b8

**Comment by Archival1** [comment]
Reproduced, looking at fixing now

**Comment by Archival1** [comment]
Fix ready for the next release.
