### ISSUE TITLE
"Buridan's ass" AI issue

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#28]
**Describe the bug**
Sorry to use philosophy paradox for describing that bug, but AI have same state - when one of npcs come closer to big stash of condoms - they just stuck, because can't able to decide which one to grab or easy distracted when finally try to do something. 

**To Reproduce**
1. Work for any levels
2. Collect stash of condoms
3. Place a stash of condoms at a route of one npc or lure that npc to near of that stash

**Expected behavior**
Choose one of condoms and don't be distracted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics Card AMD 6600xt
 - Version 1f2310b8
 
**Additional context**
If there will be donkey npc - requesting to use that bug as AI feature for them.

**Comment by naelstrof** [comment]
Ah yup, as they gain knowledge of new condoms they immediately switch states to handle it.
Now when returning a condom, they ignore alerts for all other condoms. Good investigation!
