### ISSUE TITLE
Doberman in the wall

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#29]
**Describe the bug**
At City map I have often seen doberman inside wall at one place - hallway between main room with dragon and room with lockers (near lift room and room with boxes and kangaroo). She is just standing there and after falling at lower floor. I noticed that happens with the doberman who have route at that hallway - she just to slide into that wall when casual walking. That is bug or... Harry Potter easter eggs?

**To Reproduce**
1. Load level City
2. Wait patrolling doberman near that hallway
3. See error using enchanted vision

**Screenshots**
![2024-01-30_11-22-42](https://github.com/Archival1/CV-BugReporting/assets/157325862/47466459-5581-4333-9e8a-6a4f16e25ba6)
![2024-01-30_11-23-10](https://github.com/Archival1/CV-BugReporting/assets/157325862/8605e9dd-4a62-4550-a0de-290ea211cb78)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics Card AMD 6600xt
 - Version 1f2310b8

**Comment by Archival1** [comment]
Should be fixed in the next patch
