### ISSUE TITLE
Broken hitbox of big construction

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#30]
**Describe the bug**
If jump inside on top of big construction at City map - it causes softlock. Player still able to move, but can't jump. 

**To Reproduce**
1. Load level City
2. Jump on construction from screenshot
3. See error

**Expected behavior**
Just need hitbox of normal surface

**Screenshots**
![2024-02-02_10-13-08](https://github.com/Archival1/CV-BugReporting/assets/157325862/9ba8f4a2-4c00-42c1-8b9a-f0d2f57b206b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics Card AMD 6600xt
 - Version 1f2310b8

**Comment by Archival1** [comment]
Prefab was on the wrong layer, corrected
