### ISSUE TITLE
Can get stuck/softlocked on prop in level 3: City

### ISSUE THREAD

**Issue by Seydaschu** [Archival1/CV-BugReporting#37]
**Describe the bug**
In level 3, there is a large garage room with cars and 2 'glory hole' rat helpers at the ground floor of the main building.  It is possible to jump on pipes or other props to enter some round turbine-shaped areas with railings.  If you do, it's impossible to jump or move out of the railings, and you'll be forced to quit or restart.

**To Reproduce**
1. Load level 3: City
2. Access the garage (there is a switch in the red room at the ground floor of the construction site left of mission start)
3. Jump off of pipes between the turbines to get atop turbines behind railings
4. You are stuck

**Expected behavior**
Either you should be able to jump out of this prop, or you should be blocked from entering it.

**Screenshots**
(https://github.com/Archival1/CV-BugReporting/assets/160342552/d22b4871-3ef5-4605-bcf4-29e791bbc76f)

**Comment by Archival1** [comment]
Duplicates https://github.com/Archival1/CV-BugReporting/issues/30
