### ISSUE TITLE
Carpet stains look like blood in Level 4: Station

### ISSUE THREAD

**Issue by Seydaschu** [Archival1/CV-BugReporting#39]
**Describe the bug**
In level 4, in the Priest Rat's bedroom, using any of the 3 toys puts the camera at an angle which unfortunately makes the dark stains on the floor look like blood.  The shelving behind is red, and the walls are purple, which may influence the reflection, and the camera angle is forced, making it alarming.  Viewed from above, the stains are dark.

**To Reproduce**
1. Load level 4: Station
2. Enter the Priest Rat's bedroom through a vent in the locker area
3. Use a toy on the shelf
4. The floor stains reflect a blood-red color

**Expected behavior**
Either the stains shouldn't be so shiny, or remain colorless.  Changing the props might ruin the joke of the Priest's hidden sexual obsessions!

**Screenshots**
EXPLICIT
(https://github.com/Archival1/CV-BugReporting/assets/160342552/38116812-c68b-499e-b1a7-5e58c2267e7d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Graphics Card NVIDIA GeForce GTX 1660
 - Version 551.52

**Comment by Archival1** [comment]
Easy adjustment, i'll take a look today.
