### ISSUE TITLE
Lockers do not have collision

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#42]
**Describe the bug**
The hideable lockers do not have collision other than from the intractable frontside. They also appear as if they may be opaque to NPC vision. All lockers are affected.

**To Reproduce**
1. Load any level with lockers, think all have lockers somewhere. Station does have a bunch right at the start.
2. Touch in to locker from any side other than the face

**Expected behavior**
Lockers possibly shouldn't be ghosts. :P

**Screenshots**
![image](https://github.com/Archival1/CV-BugReporting/assets/20104884/eba93ca4-400a-4789-83f3-73e4672e02e2)

**Desktop (please complete the following information):**
 - OS: Linux
 - Graphics Card: Nvidia 3090
 - Version: 61f59914

**Additional context**
New since modding update.

**Comment by Archival1** [comment]
I believe this should be fixed in the new build that went out today but will confirm shortly

**Comment by without-ordinary** [comment]
Yup, its fixed in d948076a.
