### ISSUE TITLE
Level selection screen stuck if workshop level installed

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#43]
**Describe the bug**
If a workshop level (there is only one at time of writing), the level selection screen is stuck on select contract with the message: "Mods are still downloading... Please wait." Noting happens after 10+ minutes.

**To Reproduce**
1. Subscribe to a workshop level, [which is only this one currently](https://steamcommunity.com/sharedfiles/filedetails/?id=3202412506)
2. Run game
3. Go to "Start Game"

**Expected behavior**
Get list of "contracts", which I assume would the stanard contract select screen but with an extra modded levels option.

**Screenshots**
![image](https://github.com/Archival1/CV-BugReporting/assets/20104884/49871a47-601d-4d1d-b4d3-c2b9c5361134)

**Desktop (please complete the following information):**
 - OS: Linux
 - Graphics Card: Nvidia 3090
 - Version: d948076a

**Additional context**
Its literally the first level that's been workshopped. :V

**Comment by without-ordinary** [comment]
Maps show up now, though that previous workshop map has been deleted and the only other level won't load due to a translation error or such.

https://steamcommunity.com/sharedfiles/filedetails/?id=3203061986

**Comment by naelstrof** [comment]
With the recent updates, maps should be workable. Hopefully they try to build their map again!

**Comment by without-ordinary** [comment]
Not sure if anybody has been able to make a working workshop map yet. The last 2 that were posted also didn't work (for anybody according to the comments), and have since been pulled.

I'm gonna try figuring out the SDK myself this weekend. Never used Unity before, so I'll see how that goes. :3

An open source demo level might be nice to have.

**Comment by without-ordinary** [comment]
Able to confirm that workshop levels work now. :)
