### ISSUE TITLE
The dragon's balls are bugged after being regenerated.

### ISSUE THREAD

**Issue by WolfPendragon2** [Archival1/CV-BugReporting#5]
**Describe the bug**

-After catching the dragon and reviving or regenerating it, its balls get bugged a lot, to the point of getting stuck in the same place where you catch it.

**To Reproduce**
1. Load level 'City'
2. Grab target 'after catching the dragon when it devours several NPCs'
3. Balls stuck 'only the dragon'

**Expected behavior**

-After being regenerated I expected them to only appear with their nuts full since they had devoured several NPCs. Because its nuts are bugged and it can move very quickly and without problems even though before capturing it it moved slowly because its nuts were full or overweight.

**Screenshots**
If applicable, add screenshots to help explain your problem. **If they are NSFW screenshots please don't embed them.**
I do not pass the image since as they say it would be an NSFW image

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Graphics Card: Nvidia Geforece MSI GTX 1060 6 GB
 - Version: 1/11/2024_cfdce05f

**Additional context**

-What happens is more than anything that it devours about three or four small prey and one captures it in the nuts of a playable character, one discharges it in a condom but when it regenerates or revives it appears with its nueses bugs in the place where it was caught and digested . try to take it to the place where you catch it but it continues with its bugged nuts.

**Comment by Archival1** [comment]
Reproduced & confirmed bug

**Comment by naelstrof** [comment]
Fixed in 70e18b4ab5fffbbb7226aaab0efe88ad360c9b79

(Though depending on the dragon's ball size they might get stuck, at least in a reasonable manner.)

**Comment by without-ordinary** [comment]
Repo'd this on 1f2310b8.

Let dragon get regened while having some ball mass. Balls where sitting on top of the recombob, not really stuck. Pushing them off did not result in them returning to the dragon, who was within LOS of their balls. Instead the balls acted like a push-able prop with a stretched connection to the dragon. No amount of trying to get them to snap back would work.

The balls act like a separate physical entity.

![image](https://github.com/Archival1/CV-BugReporting/assets/20104884/c0a6a89c-8e1a-48a9-81d3-e9ee9ba76564)
