### ISSUE TITLE
The dragon does not stop following the player after being devoured 3 times

### ISSUE THREAD

**Issue by WolfPendragon2** [Archival1/CV-BugReporting#6]
**Describe the bug**

-The dragon, after regenerating it more than three times, stops devouring the NPCs and only follows the player regardless of the distance.

**To Reproduce**
1. Load level 'City'
2. Grab target 'after regenerating the dragon for the third time'
3. Balls stuck 'empty nuts'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **If they are NSFW screenshots please don't embed them.**

--I don't have a screenshot of that.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Graphics Card: Nvidia Geforece MSI GTX 1060 6 GB
 - Version: 1/11/2024_cfdce05f

**Additional context**

-The error or bug is because I am trying to see if the dragon can devour all the NPCs since having the bug that I sent before its nuts were bugged I wanted to see if it asks to devour all the NPCs on the map but after regenerating it for a third or sometimes only the second only goes after the player and ignores all the npc. and it follows the player at all times despite the distance that one gives it and that I hide.

**Comment by naelstrof** [comment]
Yeah, the dragon randomly selects NPCs to track, including the player. It's omniscient when deciding, so it can just select the player regardless of their knowledge.

**Comment by WolfPendragon2** [comment]
Sorry if it takes me a while to answer but I don't use my github account much, more than anything when I do web projects, but well when I say what I mentioned is that the dragon knows where it is and doesn't stop following you despite being hidden or being at great distances. of the.

**Comment by naelstrof** [comment]
Oh it's a bug, we'll work on it! Thank you for the report

**Comment by Archival1** [comment]
This should be fixed as of today patch - the dragon no longer selects the player as a valid target when deciding to randomly vore a character and will only go after them if they detect them.
Will leave this open until im sure its solved

**Comment by WolfPendragon2** [comment]
ok, it made me happy to see that the bugs I reported appear in the patch note :)
