### ISSUE TITLE
Missing audio on Steam Deck

### ISSUE THREAD

**Issue by NoTenkyu** [Archival1/CV-BugReporting#8]
**Describe the bug**
No audio plays on Steam Deck

**To Reproduce**
Load up the game in the Steam Deck's Big Screen Mode
Enter a level

**Expected behavior**
I expected some sound to play.

**Desktop (please complete the following information):**
Steam Deck OLED, running SteamOS (Linux)

**Additional context**
Note: I was using a set of wireless headphones, but they were playing system sounds, and so should have been connected.

**Comment by naelstrof** [comment]
I had the same issue actually! I'm going to double check if it's repeatable, have you updated and rebooted the system recently?

After I updated the system, and rebooted, the audio began working normally again.

**Comment by NoTenkyu** [comment]
Well, there's no updates, and a reboot didn't seem to do anything. My options look good, so it's not something dumb like that at least. I'm gonna check if Proton does anything.

Edit: using Proton seems to fix this, and my save is unaffected. Excellent!

**Comment by NoTenkyu** [comment]
While the game itself might be a little buggy with audio, running Proton seems to fix it.

**Comment by naelstrof** [comment]
Going to leave it open as the native Linux executable still has the issue

**Comment by naelstrof** [comment]
I did a bunch of additional testing. I couldn't replicate the bug beyond the first time. An upgrade and reboot seemed to permanently fix the issue.

Unity doesn't actually have a capability to do anything besides output to the default device-- so I'm thinking this might be a steam deck issue.

**Comment by naelstrof** [comment]
I'll leave this open until we can get Steam Deck verified, it's possible that'll help reveal more information.

**Comment by without-ordinary** [comment]
I run Linux desktop only and also have a deck. No audio issues on either.

As far as the Deck not repo'ing after the first time, its very possible a random Valve furry fixed it in SteamOS. You'd be surprised how many FANG furries lurk in communities and quietly do things.
