### ISSUE TITLE
Giraffes cannot bathe in cum.

### ISSUE THREAD

**Issue by WolfPendragon2** [Archival1/CV-BugReporting#9]
**Describe the bug**

-When you devour or regenerate the giraffes, they are not affected by the cum, this happens in all the maps where they appear, in addition to the fact that you usually bug in several stations where it seems that they do things like not sit in the chairs, they block the vending machines or they are left behind. in front of the computers still working on them.

**To Reproduce**
1. Load level 'everyone where it appears the NPC's'
2. Grab target 'the giraffes'
3. Balls stuck 'not'

**Expected behavior**

-I realized that this bug happens because he is the only NPC that is not affected by cum before and after being regenerated, plus he always ends up bugging himself when he is at a station when he is caught.

**Screenshots**
If applicable, add screenshots to help explain your problem. **If they are NSFW screenshots please upload them but don't embed them (you can do this by removing the tags surrounding the image URL after you drop the image here)**

-If I can include a video it would be better since I have no way to show the bug with images since it has to be seen that bathing it in cum and being regenerated does not affect this mechanic.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Graphics Card: Nvidia GeForce  MSI GTX 1060 6 GB
 - Version: 1/11/2024_cfdce05f

**Additional context**

As I mentioned above, you have two prey, you release the cum on the NPC around you and he bathes in the cum but that NPC is not affected by that and then you devour him and when you take his condom with the giraffe NPC he regenerates As if I were not bathed in cum for nothing.

**Comment by naelstrof** [comment]
Fixed in 628aa70b4767ba0989e08f246c284e6ca84e4df1
